# Generated by Django 3.2.7 on 2022-08-04 09:28

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='photo/', validators=[app.models.Photo.validate_image])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='app.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
